import { type NextRequest, NextResponse } from "next/server"
import { getUserFromAuthHeader } from "@/lib/auth-server"

export async function POST(request: NextRequest) {
  try {
    console.log("🔄 Convert code API called")

    // Check authentication
    const authHeader = request.headers.get("authorization")
    if (!authHeader) {
      console.error("❌ No authorization header")
      return NextResponse.json({ error: "Authorization header required" }, { status: 401 })
    }

    const user = await getUserFromAuthHeader(authHeader)
    if (!user) {
      console.error("❌ Invalid user from auth header")
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    console.log("✅ User authenticated:", user.id)

    // Get Google API key from headers
    const googleApiKey = request.headers.get("X-Google-API-Key")
    console.log("🔑 API Key Debug:", {
      hasKey: !!googleApiKey,
      keyLength: googleApiKey?.length,
      keyPrefix: googleApiKey?.substring(0, 20),
    })

    if (!googleApiKey) {
      console.error("❌ No Google API key in headers")
      return NextResponse.json({ error: "Google API key required" }, { status: 400 })
    }

    if (!googleApiKey.startsWith("AIza")) {
      console.error("❌ Invalid Google API key format - should start with 'AIza'")
      return NextResponse.json(
        { error: "Invalid Google API key format. Google API keys should start with 'AIza'" },
        { status: 400 },
      )
    }

    const body = await request.json()
    const { code, fromLanguage, fromFramework, target } = body

    if (!code || !target) {
      console.error("❌ Missing code or target:", { hasCode: !!code, hasTarget: !!target })
      return NextResponse.json({ error: "Code and target are required" }, { status: 400 })
    }

    console.log("🔄 Converting code:", {
      fromLanguage,
      fromFramework,
      targetLanguage: target.language,
      targetFramework: target.framework,
      codeLength: code.length,
      actualCode: code.substring(0, 100) + "...",
    })

    // Create the actual conversion prompt
    const fromDescription = fromFramework ? `${fromLanguage} (${fromFramework})` : fromLanguage
    const toDescription = target.framework ? `${target.language} (${target.framework})` : target.language

    const conversionPrompt = `Convert the following ${fromDescription} code to ${toDescription}.

Requirements:
- Maintain the exact same functionality and logic
- Use proper syntax for ${toDescription}
- Include necessary imports/headers if needed
- Keep the same structure and flow
- Add brief comments only where absolutely necessary
- Return ONLY the converted code, no explanations or markdown

Original ${fromDescription} code:
${code}

Converted ${toDescription} code:`

    console.log("🤖 Sending conversion request to Google API...")
    console.log("📝 Prompt preview:", conversionPrompt.substring(0, 200) + "...")

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${googleApiKey}`

    const payload = {
      contents: [
        {
          parts: [
            {
              text: conversionPrompt,
            },
          ],
        },
      ],
      generationConfig: {
        temperature: 0.1, // Low temperature for consistent code conversion
        maxOutputTokens: 4000,
        topP: 0.8,
        topK: 10,
      },
    }

    const response = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    })

    console.log("📡 Google API Response:", {
      status: response.status,
      statusText: response.statusText,
    })

    if (!response.ok) {
      const errorText = await response.text()
      console.error("❌ Google API Error Response:", errorText)

      if (response.status === 400) {
        return NextResponse.json(
          { error: "Invalid Google API key or request. Please check your API key in Settings." },
          { status: 400 },
        )
      }

      if (response.status === 429) {
        return NextResponse.json({ error: "API quota exceeded. Please try again later." }, { status: 429 })
      }

      return NextResponse.json({ error: `Google API error: ${response.statusText}` }, { status: response.status })
    }

    const result = await response.json()
    console.log("✅ Google API Success")

    // Extract the generated text
    const generatedText = result.candidates?.[0]?.content?.parts?.[0]?.text

    if (!generatedText) {
      console.error("❌ No generated text in response:", result)
      return NextResponse.json({ error: "No code generated by AI" }, { status: 500 })
    }

    console.log("🎯 Generated code preview:", generatedText.substring(0, 200) + "...")

    // Clean up the response - remove any markdown code blocks if present
    let cleanedCode = generatedText.trim()

    // Remove markdown code blocks if they exist
    const codeBlockRegex = /^```[\w]*\n?([\s\S]*?)\n?```$/
    const match = cleanedCode.match(codeBlockRegex)
    if (match) {
      cleanedCode = match[1].trim()
      console.log("🧹 Removed markdown code blocks")
    }

    // Remove any leading/trailing explanatory text
    const lines = cleanedCode.split("\n")
    const codeLines = lines.filter((line: string) => {
      const trimmed = line.trim()
      return (
        trimmed &&
        !trimmed.startsWith("Here") &&
        !trimmed.startsWith("The converted") &&
        !trimmed.startsWith("This code") &&
        !trimmed.toLowerCase().includes("equivalent")
      )
    })

    const finalCode = codeLines.join("\n").trim()

    console.log("✨ Final converted code:", {
      originalLength: code.length,
      convertedLength: finalCode.length,
      target: target.label,
    })

    return NextResponse.json({
      convertedCode: finalCode,
      target: target.label,
    })
  } catch (error) {
    console.error("❌ Code conversion error:", error)

    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ error: "Conversion failed" }, { status: 500 })
  }
}
